# Generated by Django 3.1.7 on 2021-02-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ПК')),
                ('kernel_version', models.CharField(max_length=300, verbose_name='ОС')),
                ('product_type', models.CharField(max_length=50, verbose_name='Вид ОС')),
                ('product_version', models.CharField(max_length=20, verbose_name='Версия ОС')),
                ('processor_type', models.CharField(max_length=300, verbose_name='Процессор')),
                ('physical_memory', models.CharField(max_length=20, verbose_name='Объём ОП')),
                ('video_driver', models.CharField(max_length=300, verbose_name='Видео драйвер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=500, verbose_name='Название программы')),
                ('application_version', models.CharField(max_length=200, verbose_name='Версия программы')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='computers.computer')),
            ],
        ),
    ]
