# Generated by Django 3.1.7 on 2021-05-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_auto_20210307_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=500, verbose_name='Название программы')),
                ('application_version', models.CharField(max_length=200, verbose_name='Версия программы')),
            ],
        ),
        migrations.CreateModel(
            name='NewApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=500, verbose_name='Название программы')),
                ('application_version', models.CharField(max_length=200, verbose_name='Версия программы')),
            ],
        ),
    ]
