# Generated by Django 3.1.7 on 2021-05-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_deletedapplications_newapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedapplications',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_applications', to='computers.computer'),
        ),
        migrations.AddField(
            model_name='newapplications',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_applications', to='computers.computer'),
        ),
    ]
